# Beets configuration --------------------------------------------------------

library:    ~/.config/beets/music_lib.blb
directory:  /media/jacco/DATA/data/music/

import:
    # write metadata to music files
    write: yes

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete: no

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    # Controls interrupted imports. “Yes” always resumed; “no” resuming is disabled; “ask” prompt user
    resume: ask
    # controlling whether imported directories are recorded and whether these recorded directories are skipped. This corresponds to the -i flag to beet import
    incremental: no

    # Either yes or no (default), controlling whether existing metadata is discarded when a match is applied. This corresponds to the --from_scratch flag to beet import
    from_scratch: no
    none_rec_action: ask
    log: /var/log/beets/import.log

    quiet: no  # enable with command line option
    quiet_fallback: skip
    default_action: apply

    singletons: no
    languages: []
    detail: no
    flat: no

# use the release-date of the original (first) release of an album?
original_date: no

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Paths ----------------------------------------------------------------------

## Paths and filenames for music files
## relative to music directory
## %aunique{}/%if{$multidisc,Disc $disc/}
paths:
    default: %asciify{$genre}/%asciify{%title{$albumartist}}/%asciify{%title{$album}}%aunique{}/%asciify{%title{$title}}
    singleton: Non-Album/%asciify{$genre}%asciify{%title{$artist}}/%asciify{%title{$title}}
    comp: /Compilations/%asciify{$genre}/%asciify{%title{$album}}%aunique{}/%asciify{%title{$title}}

#paths:
#  # Albums/A/ASCI Artist Name, The/[YEAR] ASCI Album Name, The [EP]/01 - Track Name.mp3
#  default: 'Albums/%bucket{%upper{%left{%the{%asciify{$albumartist}},1}}}/%the{%asciify{$albumartist}}/[%if{$year,$year,0000}] %asciify{$album} %aunique{albumartist album year, albumtype label catalognum albumdisambig}/%if{$multidisc,$disc-}$track - %asciify{$title}'
#  # Singles/ASCII Artist Name, The - Track Name.mp3
#  singleton: 'Singles/%the{%asciify{$artist}} - %asciify{$title}'
#  # Compilations/[YEAR] ASCI Compilation Name, The/01-01 - Track Name.mp3
#  comp: 'Compilations/[%if{$year,$year,0000}] %the{%asciify{$album}%if{%aunique, %aunique{albumartist album year, albumtype label catalognum albumdisambig}}}/%if{$multidisc,$disc-}$track - %asciify{$title}'
#  # Sountracks/[YEAR] ASCI Soundtrack Name, The/01 - Track Name.mp3
#  albumtype:soundtrack: 'Soundtracks/[%if{$year,$year,0000}] %the{%asciify{$album}%if{%aunique, %aunique{albumartist album year, albumtype label catalognum albumdisambig}}}/%if{$multidisc,$disk-}$track - %asciify{$title}'    
#    
# replace special characters in generated filenames

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '[\(\)]': ''
    '\ ': _

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited


# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no


# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0


# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    


# Plugins --------------------------------------------------------------------

plugins: [
    discogs,
    chroma,
    fromfilename,
    acousticbrainz,
    lyrics,
    fetchart,
    embedart,
    lastgenre,
    scrub,
    mbsync,
    #mpdupdate,
    #mpdstats,
    missing,
    replaygain,
    duplicates,
    play,
    info
    # bucket,
    # inline,
    # the
]
pluginpath: []


# Plugins Config -------------------------------------------------------------

discogs:
    user_token: leYxlNYWwVhNUpLmVVadEoELkvNZhAcTNTLgBSXC

chroma:
    auto: no

acousticbrainz:
    auto: yes
    force: no
    tags: all

lyrics:
    auto: yes
    fallback: 'no_genre'
    force: yes
    google_API_key: AZERTYUIOPQSDFGHJKLMWXCVBN1234567890_ab
    google_engine_ID: 009217259823014548361:lndtuqkycfu

echonest_tempo:
    auto: yes

lastgenre:
    whitelist: ~/.config/beets/genres.txt
    canoncical: ~/.config/beets/genres-tree.yaml
    fallback: ''
    source: artist

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder

embedart:
    auto: yes
    ifempty: yes
    maxwidth: 300

replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes
    albumgain: yes

scrub:
    auto: yes

# required for mpdstats
#mpd:
#    host: localhost
#    port: 6600
#    password:  # none

#mpdstats:
#    rating: False
    # two ratings are calculated:
    # "rolling" based on recent development
    # "stable" based on all-time development
    # rating mix 0.0 is all "rolling", 1.0 is all "stable"
#    rating_mix: 0.75

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

duplicates:
    album: no
#    checksum: no  # expensive

play:
    # command: /usr/bin/command --option1 --option2 some_other_option
    command: /usr/bin/vlc
    # command: /usr/bin/totem

# hoort bij inline plugin, tbv create "disc N" directories for multi-disc albums
# uitgezet omdat file wordt gerenaamd ipv folder 
    #item_field:
#         multidisc: 1 if disctotal > 1 else 0
# Inline plugin multidisc template
#item_fields:
#  multidisc: 1 if disctotal > 1 else 0
# 
## Collects all special characters into single bucket
#bucket:
#  bucket_alpha:
#    - _
#    - A
#    - B
#    - C
#    - D
#    - E
#    - F
#    - G
#    - H
#    - I
#    - J
#    - K
#    - L
#    - M
#    - N
#    - O
#    - P
#    - Q
#    - R
#    - S
#    - T
#    - U
#    - V
#    - W
#    - X
#    - Y
#    - Z
#  bucket_alpha_regex:
#    '_': ^[^A-Z]
#
